---
Categories:
Description: ""
Tags:
- Test
date: 2017-04-20
title: "Test page"
---

## This is a header

This is just some plain old text. 

This is a graph:

```{r, echo = FALSE, message=F, warning = F, out.width = "90%", out.height = "380px"}
library(plotly);library(Quandl);library(lubridate)
source("~/Dropbox/Work/coffeestats/scripts/setQuandl.R")
cof <- Quandl("CHRIS/ICE_KC2", start_date = today() - years(2))
cof %>% 
    plot_ly(x = ~Date, y = ~Settle, type = "scatter", mode = "lines", line = list(color = "#6a9fb5")) %>% 
    layout(title = "ICE/KC Second month contract", 
           yaxis = list(title = "US cents/lb"),
           xaxis = list(title = ""),
           font = list(family = "sans-serif", color = "#515151"))
```


```{r, echo = F, message = F, warning = F}
htmltools::HTML("<p class = 'message'>This is a message</p>")
```


>  This is an interesting quote

>  Huh, fancy that

```{r, echo = TRUE, message = FALSE, warning = FALSE}
# This is a code chunk
library(tidyverse)
x <- (2 * 2)
print(x)
```






