---
Categories:
- Datasets
Description: "A draft visualization inspired by the Australian Open final between Federer and Nadal."
Tags:
- Test
- R
- Plotly
date: 2017-01-26T16:19:23Z
title: "Tennis"
thumbnail: 'tennis-thumbnail.png'
draft: true
---
 
A draft visualization inspired by the Australian Open final between Federer and Nadal.

```{r, echo = FALSE, out.width = "100%"}
htmltools::HTML("{{< tweet 824984527869181954 >}}")
```

Should be an interactive version here:

```{r, echo = FALSE, message = FALSE, warning = FALSE, out.width = "100%"}
library(tidyverse);library(plotly);library(lubridate)
tennisRaw <- read_csv("~/Dropbox/R/R_working-directory/tennis/tennis.csv")

tennis <- tennisRaw %>%
    gather(., -Date, -Tournament, -Round, key = result, value = Player) %>%
    filter(grepl("Federer|Nadal", Player)) %>%
    mutate(Round = ordered(Round,
                           levels = c("1st Round", "2nd Round", "3rd Round", "4th Round",
                                      "Quarterfinals", "Semifinals", "The Final")),
           Tournament = ordered(Tournament,
                                levels = c("Australian Open", "French Open",
                                           "Wimbledon", "US Open")),
           Date = dmy(ifelse(Tournament == "Australian Open",
                             paste0("01-01-", year(Date)),
                             ifelse(Tournament == "French Open",
                                    paste0("01-04-", year(Date)),
                                    ifelse(Tournament == "Wimbledon",
                                           paste0("01-07-", year(Date)),
                                           paste0("01-10-", year(Date)))))),
           Player = gsub("([A-Za-z]+).*", "\\1", Player)
    ) %>%
    group_by(Date, Tournament, Player) %>%
    summarise(Progress = max(Round)) %>%
    ungroup() %>%
    spread(., key = Player, value = Progress) %>%
    gather(., -Date, -Tournament, key = Player, value = Progress) %>%
    mutate(Progress = ordered(Progress,
                              levels = c("1st Round", "2nd Round", "3rd Round",
                                         "4th Round", "Quarterfinals", "Semifinals",
                                         "The Final")))

tennis <- rbind(tennis,
                c("2017-01-01", "Australian Open", "Federer", "The Final"),
                c("2017-01-01", "Australian Open", "Nadal", "The Final"))

plotlyData <- tennis %>%
    spread(., key = Player, value = Progress) %>%
    mutate(Both = ifelse(Federer == "The Final" & Nadal == "The Final",
                         "The Final", NA)) %>%
    gather(., -Date, -Tournament, key = Player, value = Progress) %>%
    mutate(Progress = ordered(Progress,
                              levels = levels(tennis$Progress))) %>%
    spread(key = Player, value = Progress)

plot_ly() %>%
    add_trace(
        data = plotlyData,
        x = ~Date, y = ~Federer, name = "Federer",
        type = "scatter", mode = "lines+markers",
        line = list(color = "#e37222"),
        text = ~paste(Tournament, year(Date)),
        hoverinfo = "text"
    ) %>%
    add_trace(
        data = plotlyData,
        x = ~Date, y = ~Nadal, name = "Nadal",
        type = "scatter", mode = "lines+markers",
        line = list(color = "#08899e"),
        text = ~paste(Tournament, year(Date)),
        hoverinfo = "text"
    ) %>%
    add_trace(
        data = plotlyData,
        x = ~Date, y = ~Both, name = "Both",
        type = "scatter", mode = "markers",
        marker = list(
            size = 14,
            color = "white",
            symbol = "circle",
            opacity = 1,
            line = list(
                color = "red",
                width = 4
            )),
            text = ~paste(Tournament, year(Date)),
            hoverinfo = "text"
        ) %>%
            layout(
                title = "Federer and Nadal haven't met in the final of a Grand Slam <br>since the French Open in 2011 <br> ",
                xaxis = list(
                    title = "",
                    range = c("2012-01-01", "2018-01-01"),
                    showgrid = FALSE
                ),
                yaxis = list(
                    title = ""
                ),
                margin = list(
                    l = 85
                )
            )



```
